version: "2"

checks:
  method-lines:
    enabled: true
    config:
      threshold: 25
  argument-count:
    enabled: true
    config:
      threshold: 3
  method-complexity:
    enabled: true
    config:
      threshold: 10
exclude_patterns:
- "test_**"
- "test_*"
- "**/test/"
- "**/tests/"
- "Tests/"